using System.Security.Cryptography;
using System.Text;
using Shortly.Application.Interfaces;

namespace Shortly.Endpoints;

public static class UrlRedirectEndpoint
{
    public static RouteHandlerBuilder MapUrlRedirect(this WebApplication app)
    {
        return app.MapGet("/{shortUrl}", async (string shortUrl, HttpContext context, ILinkService linkService) =>
        {
            if (!IsValidShortCode(shortUrl))
            {
                // RFC 7807 keeps invalid short-code errors machine-readable and content-negotiated as application/problem+json.
                return Results.Problem(
                    title: "Invalid short code",
                    statusCode: StatusCodes.Status400BadRequest,
                    detail: "The short code must be a 6-12 character Base62 token generated by Shortly.");
            }

            Application.DTOs.LinkResponse link;
            try
            {
                link = await linkService.GetLink(shortUrl);
            }
            catch (KeyNotFoundException)
            {
                return Results.Problem(
                    title: "Short link not found",
                    statusCode: StatusCodes.Status404NotFound,
                    detail: $"No short link exists for '{shortUrl}'.");
            }

            var etag = ComputeETag(link.ShortUrl, link.Url);
            var lastModified = DateTime.SpecifyKind(link.CreatedAt, DateTimeKind.Utc);
            lastModified = lastModified.AddTicks(-(lastModified.Ticks % TimeSpan.TicksPerSecond));

            context.Response.Headers.CacheControl = "private, must-revalidate";
            context.Response.Headers.ETag = etag;
            context.Response.Headers.LastModified = lastModified.ToString("R");

            var ifNoneMatch = context.Request.Headers.IfNoneMatch;
            if (ifNoneMatch.Count > 0)
            {
                if (ifNoneMatch.Any(v => v == etag || v == "*"))
                    return Results.StatusCode(StatusCodes.Status304NotModified);
            }
            else if (context.Request.Headers.TryGetValue("If-Modified-Since", out var raw)
                     && DateTime.TryParse(raw, out var ifModifiedSince)
                     && lastModified <= ifModifiedSince.ToUniversalTime())
            {
                return Results.StatusCode(StatusCodes.Status304NotModified);
            }

            await linkService.IncrementClicks(link.Id);
            return Results.Redirect(link.Url);
        });
    }

    private static bool IsValidShortCode(string shortUrl)
        => shortUrl.Length is >= 6 and <= 12
           && shortUrl.All(c => c is >= '0' and <= '9'
                                or >= 'A' and <= 'Z'
                                or >= 'a' and <= 'z');

    private static string ComputeETag(string shortUrl, string url)
    {
        var input = $"{shortUrl}:{url}";
        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(input));
        return $"\"{Convert.ToHexString(hash)[..16]}\"";
    }
}